"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AsideBar from "@/components/AsideBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <div className="w-full h-screen">
                    <Navbar />
                    <div className="relative w-full h-screen pt-14 bg-gray-300 flex">
                        <AsideBar></AsideBar>
                        {/* <Sidebar toggle={isMenuOpen}>
                            <SideBarHeader />
                            <SideBarFooter />
                        </Sidebar> */}
                        <div className="w-full h-full overflow-auto max-w-full max-h-full p-4 flex-1">
                            {children}
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
